production:
  clients:
    default:
      database: services_presenters_api_development
      hosts:
        - localhost:27017
  options:

development:
  clients:
    default:
      database: services_presenters_api_development
      hosts:
        - localhost:27017
  options:

test:
  clients:
    default:
      database: spiderdoorapi_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
